### ISSUE TITLE
Add icon for djs files

### ISSUE THREAD

**Issue by AnEmortalKid** [dogescript/vscode-dogescript#3]
Add icon

Use DJS in letters and look at the color github uses for dogescript

**Comment by AnEmortalKid** [comment]
https://code.visualstudio.com/api/extension-capabilities/theming#adding-a-new-icon-theme

**Comment by AnEmortalKid** [comment]
```yaml
Dogescript:
  type: programming
  color: "#cca760"
  extensions:
  - ".djs"
  tm_scope: none
  ace_mode: text
  language_id: 90
  ```
